CREATE DATABASE IF NOT EXISTS bikes;
USE bikes;

DROP TABLE IF EXISTS Category;
CREATE TABLE IF NOT EXISTS bikes.Category (
  Id INT NOT NULL AUTO_INCREMENT,
  Name VARCHAR(45) NOT NULL,
  Image VARCHAR(300) NOT NULL,
  PRIMARY KEY (Id),
  UNIQUE INDEX Id_UNIQUE (Id ASC) VISIBLE)

ENGINE = InnoDB;

DROP TABLE IF EXISTS Brand;
CREATE TABLE IF NOT EXISTS bikes.Brand (
  Id INT NOT NULL AUTO_INCREMENT,
  Name VARCHAR(45) NOT NULL,
  Image VARCHAR(300) NOT NULL,
  PRIMARY KEY (Id)
)
ENGINE = InnoDB;


DROP TABLE IF EXISTS Product;
CREATE TABLE IF NOT EXISTS bikes.Product (
  Id INT UNSIGNED  NOT NULL AUTO_INCREMENT,
  Name VARCHAR(115) NOT NULL,
  Desciption LONGTEXT NOT NULL,
  Price DECIMAL NOT NULL,
  Stock INT NOT NULL,
  Sold INT NOT NULL DEFAULT 0,
  Image VARCHAR(300) NOT NULL,
  Brand_Id INT NOT NULL,
  Category_Id INT NOT NULL,
  PRIMARY KEY (Id),
  CONSTRAINT fk_Product_Brand
    FOREIGN KEY (Brand_Id)
    REFERENCES bikes.Brand (Id),
  CONSTRAINT fk_Product_Category
    FOREIGN KEY (Category_Id)
    REFERENCES bikes.Category (Id))
ENGINE = InnoDB;

DROP TABLE IF EXISTS orders;
CREATE TABLE IF NOT EXISTS bikes.Orders (
  Id INT NOT NULL AUTO_INCREMENT,
  Product_Id INT UNSIGNED  NOT NULL,
  Size VARCHAR(2) NOT NULL,
  Subtotal DECIMAL NOT NULL,
  QST DECIMAL NOT NULL,
  GST DECIMAL NOT NULL,
  Total DECIMAL NOT NULL,
  PRIMARY KEY (Id),
  CONSTRAINT fk_Orders_Product
    FOREIGN KEY (Product_Id)
    REFERENCES bikes.Product(Id)
    )
ENGINE = InnoDB;

DROP TABLE IF EXISTS Admins;
CREATE TABLE IF NOT EXISTS bikes.Admins (
  Id INT NOT NULL AUTO_INCREMENT,
  Name VARCHAR(45) NOT NULL,
  Username VARCHAR(45) NOT NULL,
  Password VARCHAR(45) NOT NULL,
  Salt VARCHAR(45) NOT NULL,
  PRIMARY KEY (Id),
  UNIQUE INDEX Id_UNIQUE (Id ASC) VISIBLE)
ENGINE = InnoDB;

